// Manages a LiteLLM proxy that translates Codex's Responses requests into an
// upstream that only speaks Chat Completions.
//
// This project still does not carry model traffic. It writes LiteLLM's config
// file — which is exactly the kind of work it already does for Pi and Codex —
// and can start and stop the process. The translation itself belongs to
// LiteLLM, so Codex's weekly changes to its side of the wire are their
// maintenance burden rather than ours.

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { spawn } from "node:child_process";

import { readJson, writeJsonAtomic, writeTextAtomic } from "./atomic-files.mjs";

export const DEFAULT_BRIDGE_PORT = 43210;
// LiteLLM's own default is 4000, which is commonly already taken; and its
// default host is 0.0.0.0, which would put an unauthenticated proxy holding the
// user's upstream key on every interface. Both are overridden explicitly.
const BRIDGE_HOST = "127.0.0.1";
const KEY_ENV_VAR = "PPM_BRIDGE_UPSTREAM_KEY";

function yamlString(value) {
  return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

// Emits the config LiteLLM needs to expose /v1/responses over a
// chat-completions-only upstream. The upstream key is referenced through the
// environment and never written into the file.
export function renderLitellmConfig({ models, upstreamBaseUrl }) {
  const lines = [
    "# Generated by Pi Provider Manager. Edits are overwritten on the next save.",
    "#",
    "# use_chat_completions_api routes LiteLLM's /v1/responses endpoint through",
    "# the upstream's /v1/chat/completions, which is what Codex needs from a",
    "# provider that never implemented the Responses API.",
    "model_list:",
  ];
  for (const model of models) {
    lines.push(`  - model_name: ${yamlString(model.id)}`);
    lines.push("    litellm_params:");
    lines.push(`      model: ${yamlString(`openai/${model.upstreamId || model.id}`)}`);
    lines.push(`      api_base: ${yamlString(upstreamBaseUrl)}`);
    lines.push(`      api_key: ${yamlString(`os.environ/${KEY_ENV_VAR}`)}`);
    lines.push("      use_chat_completions_api: true");
  }
  return `${lines.join("\n")}\n`;
}

export function bridgeBaseUrl(port) {
  return `http://${BRIDGE_HOST}:${port}/v1`;
}

export function createBridgeRunner({ dir }) {
  const configPath = path.join(dir, "pi-provider-manager-litellm.yaml");
  // Runtime state, deliberately outside the config revision: starting or
  // stopping the proxy must not invalidate a draft someone is editing.
  const statePath = path.join(dir, "pi-provider-manager-bridge.json");
  const logPath = path.join(dir, "pi-provider-manager-bridge.log");
  const binary = process.env.PI_PROVIDER_MANAGER_LITELLM || "litellm";

  function readState() {
    const state = readJson(statePath);
    return {
      pid: Number.isInteger(state.pid) ? state.pid : 0,
      port: Number.isInteger(state.port) ? state.port : 0,
      providerId: typeof state.providerId === "string" ? state.providerId : "",
    };
  }

  // A recorded pid is not proof: pids are reused, and killing whatever
  // inherited it would be someone else's process. Only a process whose command
  // line still names our config file counts as ours.
  function isOurProcess(pid) {
    if (!pid) return false;
    try {
      process.kill(pid, 0);
    } catch {
      return false;
    }
    try {
      const cmdline = fs.readFileSync(`/proc/${pid}/cmdline`, "utf8");
      return cmdline.includes(configPath);
    } catch {
      // No procfs (macOS, Windows). Liveness is all we can honestly claim, so
      // report it and refuse to kill on that basis alone.
      return null;
    }
  }

  function status() {
    const state = readState();
    const ours = isOurProcess(state.pid);
    return {
      configPath,
      logPath,
      binary,
      port: state.port,
      providerId: state.providerId,
      pid: state.pid,
      running: ours === true,
      // Alive but unverifiable: we will report it and let the user stop it.
      unverified: ours === null && state.pid > 0,
    };
  }

  function writeConfig({ models, upstreamBaseUrl }) {
    writeTextAtomic(configPath, renderLitellmConfig({ models, upstreamBaseUrl }));
    return configPath;
  }

  function start({ providerId, port, upstreamKey }) {
    const current = status();
    if (current.running && current.port === port) return current;
    if (!fs.existsSync(configPath)) throw new Error("桥的配置文件还没有生成，请先保存这个供应商。");

    const out = fs.openSync(logPath, "a");
    const child = spawn(binary, ["--config", configPath, "--host", BRIDGE_HOST, "--port", String(port)], {
      // Detached so the proxy outlives this manager: closing the config editor
      // must not cut Codex off mid-session.
      detached: true,
      stdio: ["ignore", out, out],
      env: { ...process.env, [KEY_ENV_VAR]: upstreamKey || "" },
    });
    // spawn reports a missing binary asynchronously. Without a listener that
    // "error" event is re-thrown as an uncaught exception and takes the whole
    // server down, so it is recorded where the user will look for it instead.
    child.on("error", (error) => {
      const hint = error.code === "ENOENT"
        ? `找不到 ${binary}。装好 LiteLLM 后，若它不在 PATH 上，用 PI_PROVIDER_MANAGER_LITELLM 指定完整路径。`
        : error.message;
      try {
        fs.appendFileSync(logPath, `\n[pi-provider-manager] ${hint}\n`);
        writeJsonAtomic(statePath, {});
      } catch {}
    });
    fs.closeSync(out);
    child.unref();
    writeJsonAtomic(statePath, { pid: child.pid, port, providerId });
    return { ...status(), pid: child.pid, port, providerId, starting: true };
  }

  function stop() {
    const state = readState();
    const ours = isOurProcess(state.pid);
    if (ours !== true) {
      // Either it is gone, or we cannot prove the pid is still ours. Clearing
      // the record is safe; signalling an unidentified process is not.
      writeJsonAtomic(statePath, {});
      if (ours === null) throw new Error("无法确认该进程仍属于本管理器，未发送停止信号。请手动结束它。");
      return { stopped: false };
    }
    try {
      process.kill(state.pid, "SIGTERM");
    } catch (error) {
      if (error.code !== "ESRCH") throw error;
    }
    writeJsonAtomic(statePath, {});
    return { stopped: true };
  }

  return { configPath, logPath, status, writeConfig, start, stop, isOurProcess };
}

export function bridgeKeyEnvVar() {
  return KEY_ENV_VAR;
}
