// Manages a LiteLLM proxy that translates Codex's Responses requests into an
// upstream that only speaks Chat Completions.
//
// This project still does not carry model traffic. It writes LiteLLM's config
// file — which is exactly the kind of work it already does for Pi and Codex —
// and can start and stop the process. The translation itself belongs to
// LiteLLM, so Codex's weekly changes to its side of the wire are their
// maintenance burden rather than ours.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import process from "node:process";
import { spawn } from "node:child_process";

import { readJson, writeJsonAtomic, writeTextAtomic } from "./atomic-files.mjs";

export const DEFAULT_BRIDGE_PORT = 43210;
// LiteLLM's own default is 4000, which is commonly already taken; and its
// default host is 0.0.0.0, which would put an unauthenticated proxy holding the
// user's upstream key on every interface. Both are overridden explicitly.
const BRIDGE_HOST = "127.0.0.1";
const KEY_ENV_VAR = "PPM_BRIDGE_UPSTREAM_KEY";

function yamlString(value) {
  return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

// Emits the config LiteLLM needs to expose /v1/responses over a
// chat-completions-only upstream. The upstream key is referenced through the
// environment and never written into the file.
export function renderLitellmConfig({ models, upstreamBaseUrl }) {
  const lines = [
    "# Generated by Pi Provider Manager. Edits are overwritten on the next save.",
    "#",
    "# use_chat_completions_api routes LiteLLM's /v1/responses endpoint through",
    "# the upstream's /v1/chat/completions, which is what Codex needs from a",
    "# provider that never implemented the Responses API.",
    "model_list:",
  ];
  for (const model of models) {
    lines.push(`  - model_name: ${yamlString(model.id)}`);
    lines.push("    litellm_params:");
    lines.push(`      model: ${yamlString(`openai/${model.upstreamId || model.id}`)}`);
    lines.push(`      api_base: ${yamlString(upstreamBaseUrl)}`);
    lines.push(`      api_key: ${yamlString(`os.environ/${KEY_ENV_VAR}`)}`);
    lines.push("      use_chat_completions_api: true");
  }
  return `${lines.join("\n")}\n`;
}

export function bridgeBaseUrl(port) {
  return `http://${BRIDGE_HOST}:${port}/v1`;
}

// PEP 668 stops Debian and Ubuntu — which is what WSL is — from installing
// LiteLLM system-wide, so it usually ends up in a virtualenv or under pipx and
// not on PATH. Rather than making everyone discover PI_PROVIDER_MANAGER_LITELLM
// the hard way, look where those installers actually put it.
const LITELLM_CANDIDATES = [
  // pipx, and anything else that links into the user's bin directory.
  ".local/bin/litellm",
  // The virtualenv layout both READMEs suggest.
  ".local/litellm/bin/litellm",
  ".local/share/litellm/bin/litellm",
  ".venvs/litellm/bin/litellm",
  "venvs/litellm/bin/litellm",
];

export function findLitellm(home = os.homedir()) {
  for (const candidate of LITELLM_CANDIDATES) {
    const absolute = path.join(home, candidate);
    try {
      fs.accessSync(absolute, fs.constants.X_OK);
      return absolute;
    } catch {}
  }
  // Fall through to PATH resolution by the shell-less spawn.
  return "litellm";
}

export function createBridgeRunner({ dir }) {
  const configPath = path.join(dir, "pi-provider-manager-litellm.yaml");
  // Runtime state, deliberately outside the config revision: starting or
  // stopping the proxy must not invalidate a draft someone is editing.
  const statePath = path.join(dir, "pi-provider-manager-bridge.json");
  const logPath = path.join(dir, "pi-provider-manager-bridge.log");
  // Resolved on every read rather than once at startup. LiteLLM is usually
  // installed *after* the manager has been opened for the first time — that is
  // the order the README itself suggests — and a path frozen at startup means
  // that install is never noticed. Worse, the launcher reuses an already
  // running manager, so there is no obvious way to make it reconsider.
  function resolveBinary() {
    return process.env.PI_PROVIDER_MANAGER_LITELLM || findLitellm();
  }

  // Whether a started process can later be proven to be ours. Probed rather
  // than inferred from the platform: procfs is the actual capability the
  // ownership check needs, and it is what decides whether supervising a
  // long-lived process here is honest at all.
  const supervisable = (() => {
    try {
      return fs.readFileSync(`/proc/${process.pid}/cmdline`, "utf8").length > 0;
    } catch {
      return false;
    }
  })();

  // What to run by hand where the manager cannot supervise. The upstream key is
  // named, never included: it lives in the manager's store and must not travel
  // to a browser or a screenshot.
  function manualCommand(binary, port) {
    return `${KEY_ENV_VAR}=<上游 key> ${binary} --config ${configPath} --host ${BRIDGE_HOST} --port ${port || DEFAULT_BRIDGE_PORT}`;
  }

  // Old LiteLLM releases have no Responses-to-Chat bridging at all: 1.79.0
  // forwards /v1/responses straight to the upstream and surfaces the upstream's
  // 404, which reads like a broken gateway rather than a too-old proxy. Report
  // the version so that is diagnosable without guessing.
  //
  // `litellm --version` takes eight to nine seconds — it imports a very large
  // Python package — and status() is reached by every /api/state. So the probe
  // runs in the background and the answer is reported once it lands: no request
  // ever waits on it, and a binary that never answers costs nothing.
  let probedBinary;
  let cachedVersion;
  let versionProbe;
  function detectedVersion(binary) {
    // A newly discovered executable is a different question, so the previous
    // answer — including a failed probe against a binary that did not exist
    // yet — must not be reported for it.
    if (binary !== probedBinary) {
      probedBinary = binary;
      cachedVersion = undefined;
      versionProbe = undefined;
    }
    if (cachedVersion !== undefined) return cachedVersion;
    if (!versionProbe) {
      versionProbe = new Promise((resolve) => {
        const settle = (value) => {
          cachedVersion = value;
          resolve(value);
        };
        let child;
        try {
          child = spawn(binary, ["--version"], { stdio: ["ignore", "pipe", "ignore"] });
        } catch {
          settle("");
          return;
        }
        let output = "";
        const timer = setTimeout(() => {
          child.kill();
          settle("");
        }, 60_000);
        timer.unref?.();
        child.stdout.on("data", (chunk) => { output += chunk; });
        child.on("error", () => { clearTimeout(timer); settle(""); });
        child.on("close", () => { clearTimeout(timer); settle(output.match(/\d+\.\d+\.\d+/)?.[0] || ""); });
      });
    }
    // Still running. Report nothing rather than making the caller wait.
    return "";
  }

  // Exposed for tests: resolves once the background probe has an answer.
  function versionSettled() {
    detectedVersion(resolveBinary());
    return versionProbe;
  }

  function readState() {
    const state = readJson(statePath);
    return {
      pid: Number.isInteger(state.pid) ? state.pid : 0,
      port: Number.isInteger(state.port) ? state.port : 0,
      providerId: typeof state.providerId === "string" ? state.providerId : "",
    };
  }

  // A recorded pid is not proof: pids are reused, and killing whatever
  // inherited it would be someone else's process. Only a process whose command
  // line still names our config file counts as ours.
  function isOurProcess(pid) {
    if (!pid) return false;
    try {
      process.kill(pid, 0);
    } catch {
      return false;
    }
    try {
      const cmdline = fs.readFileSync(`/proc/${pid}/cmdline`, "utf8");
      return cmdline.includes(configPath);
    } catch {
      // No procfs (macOS, Windows). Liveness is all we can honestly claim, so
      // report it and refuse to kill on that basis alone.
      return null;
    }
  }

  function status() {
    const state = readState();
    const ours = isOurProcess(state.pid);
    const binary = resolveBinary();
    return {
      configPath,
      logPath,
      binary,
      version: detectedVersion(binary),
      binarySource: process.env.PI_PROVIDER_MANAGER_LITELLM
        ? "PI_PROVIDER_MANAGER_LITELLM"
        : binary === "litellm" ? "PATH" : "discovered",
      supervisable,
      manualCommand: manualCommand(binary, state.port),
      port: state.port,
      providerId: state.providerId,
      pid: state.pid,
      running: ours === true,
      // Alive but unverifiable: we will report it and let the user stop it.
      unverified: ours === null && state.pid > 0,
    };
  }

  function writeConfig({ models, upstreamBaseUrl }) {
    writeTextAtomic(configPath, renderLitellmConfig({ models, upstreamBaseUrl }));
    return configPath;
  }

  function start({ providerId, port, upstreamKey }) {
    if (!supervisable) {
      throw new Error("本平台无法确认进程归属，因此不托管桥进程。配置已生成，请按界面给出的命令自行运行。");
    }
    const current = status();
    if (current.running && current.port === port) return current;
    if (!fs.existsSync(configPath)) throw new Error("桥的配置文件还没有生成，请先保存这个供应商。");

    const binary = resolveBinary();
    const out = fs.openSync(logPath, "a");
    const child = spawn(binary, ["--config", configPath, "--host", BRIDGE_HOST, "--port", String(port)], {
      // Detached so the proxy outlives this manager: closing the config editor
      // must not cut Codex off mid-session.
      detached: true,
      stdio: ["ignore", out, out],
      env: { ...process.env, [KEY_ENV_VAR]: upstreamKey || "" },
    });
    // spawn reports a missing binary asynchronously. Without a listener that
    // "error" event is re-thrown as an uncaught exception and takes the whole
    // server down, so it is recorded where the user will look for it instead.
    child.on("error", (error) => {
      const hint = error.code === "ENOENT"
        ? `找不到 ${binary}。装好 LiteLLM 后，若它不在 PATH 上，用 PI_PROVIDER_MANAGER_LITELLM 指定完整路径。`
        : error.message;
      try {
        fs.appendFileSync(logPath, `\n[pi-provider-manager] ${hint}\n`);
        writeJsonAtomic(statePath, {});
      } catch {}
    });
    fs.closeSync(out);
    child.unref();
    writeJsonAtomic(statePath, { pid: child.pid, port, providerId });
    return { ...status(), pid: child.pid, port, providerId, starting: true };
  }

  function stop() {
    const state = readState();
    const ours = isOurProcess(state.pid);
    if (ours !== true) {
      // Either it is gone, or we cannot prove the pid is still ours. Clearing
      // the record is safe; signalling an unidentified process is not.
      writeJsonAtomic(statePath, {});
      if (ours === null) throw new Error("无法确认该进程仍属于本管理器，未发送停止信号。请手动结束它。");
      return { stopped: false };
    }
    try {
      process.kill(state.pid, "SIGTERM");
    } catch (error) {
      if (error.code !== "ESRCH") throw error;
    }
    writeJsonAtomic(statePath, {});
    return { stopped: true };
  }

  return { configPath, logPath, status, writeConfig, start, stop, isOurProcess, versionSettled };
}

export function bridgeKeyEnvVar() {
  return KEY_ENV_VAR;
}
